# Generated by Django 2.1 on 2018-08-22 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailynews',
            name='datetime',
            field=models.DateTimeField(verbose_name='日期时间'),
        ),
        migrations.AlterField(
            model_name='dailynews',
            name='forecast',
            field=models.CharField(max_length=30, verbose_name='预测值'),
        ),
        migrations.AlterField(
            model_name='dailynews',
            name='previous',
            field=models.CharField(max_length=30, verbose_name='前值'),
        ),
        migrations.AlterField(
            model_name='dailynews',
            name='star',
            field=models.IntegerField(verbose_name='重要性'),
        ),
        migrations.AlterField(
            model_name='dailynews',
            name='title',
            field=models.CharField(max_length=255, verbose_name='标题内容'),
        ),
        migrations.AlterField(
            model_name='dailynews',
            name='value',
            field=models.CharField(max_length=30, verbose_name='现值'),
        ),
    ]
