# Generated by Django 2.1 on 2018-08-23 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mainapp', '0003_delete_dailynews'),
    ]

    operations = [
        migrations.CreateModel(
            name='dailyNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='标题内容')),
                ('datetime', models.DateTimeField(verbose_name='日期时间')),
                ('value', models.CharField(max_length=30, verbose_name='现值')),
                ('forecast', models.CharField(max_length=30, verbose_name='预测值')),
                ('previous', models.CharField(max_length=30, verbose_name='前值')),
                ('star', models.IntegerField(verbose_name='重要性')),
            ],
            options={
                'db_table': 'dailynews',
                'ordering': ['datetime'],
            },
        ),
    ]
