# Generated by Django 2.1 on 2018-08-23 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_dailynews'),
    ]

    operations = [
        migrations.DeleteModel(
            name='dailyNews',
        ),
    ]
